## Recurrent Neural Networks (RNN) Keras DEMO
Tensorflow KERAS has built in RRN layers that we can use we will use them to create our model


In [1]:
"""
    Import Modules
"""
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow._api.v2 import random



In [2]:

"""
    Scalar: a single number
    Vector: a set of numbers indicating direction and intensity such as wind speed
    Matrix: a d-dimensional array of numbers
    Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)
"""

"""
    Method of creating a tensors:
    1. Using tf.constant()
    2. Using tf.Variable()
    3. Using tf.placeholder()
"""

"""matrix 2d array of numbers"""
example_matrix = tf.constant(
    [ 
        [1, 2, 3], 
        [4, 5, 6],
        [8, 4, 2]
    ],
    dtype=tf.float32
    )

example_matrix, example_matrix.ndim

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [8., 4., 2.]], dtype=float32)>,
 2)

In [3]:
"""tensor is an n-dimensional array"""
tensor = tf.constant(
    [
        [
            [ 1,2,3 ],
            [ 4,5,6 ]
        ],
        [
            [ 7,8,9 ],
            [ 10,11,12 ]
        ],
        [
            [ 13,14,15 ],
            [ 16,17,18 ]
        ]
    ]
)

print(tensor)
print(tensor.ndim)


tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
3


In [4]:

"""
    tf.Variable
"""

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

#print(changeable_tensor, "\n", unchangeable_tensor)
print(changeable_tensor)

# changeable_tensor[0] = 7, will not work we must use assign
changeable_tensor[0].assign(7)

print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>


In [5]:
"""
    NOTE: Rarely in practice will you need to decide weather to use tf.Variable or tf.constant to create tensors.
    as tensorflow does this for you, However

    if in doubt use tf.constant and change it later if needed
"""

"""
    Creating random tensors
"""

random_1 = tf.random.Generator.from_seed(42) # we set a seed to get reproducible results
random_1 = random.normal(shape=(3,2))
print(random_1)

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
print(random_2)

print(random_1 == random_2)

tf.Tensor(
[[-0.99764645  0.43769377]
 [ 1.208841   -1.892482  ]
 [-0.44301403  0.60031396]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[False False]
 [False False]
 [False False]], shape=(3, 2), dtype=bool)


In [6]:
"""
    Shuffling
    Valuable :: useful for repeating experiments using seeds and shuffle data in exact same instances
    View TF documentation for more details
"""
not_shuffled = tf.constant(
    [
        [10,7],
        [3,4],
        [2,5]

    ]
)

print(tf.random.shuffle(not_shuffled,seed=42))

tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)


In [7]:
"""
    TF/Numpy Ones/Zeros
    creates a tensor filled with ones of the specified shape
"""
print(tf.ones([10,7]))
print(tf.zeros([10,7]))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(10, 7), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]], shape=(10, 7), dtype=float32)


In [8]:
"""
    Turn Numpy Array into tensors
    NOTE: Numpay arrays run upon the CPU while tensors 
    can be run on the GPU which is much faster numerical computing
"""
numpy_array = np.arange(1,25, dtype=np.int32)
print(numpy_array)
A = tf.constant(numpy_array, shape=(2,3,4))
B = tf.constant(numpy_array, shape=(2,3,4))
print(A,B)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32) tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [9]:
"""
    Getting information from tensors
"""
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [10]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [11]:
# get the first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [12]:
# create a rank 2 tensor (2 dimensional tensor)
rank_2_tensor = tf.constant([
    [15, 5],
    [9, 21]
])#tf.zeros(shape=[2,2])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15,  5],
       [ 9, 21]])>

In [13]:
# Get the last item of each row of our rank 2 tensor
# : = all items in the dimension
# -1 = only the last element from each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 21])>

In [14]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[15],
        [ 5]],

       [[ 9],
        [21]]])>

In [15]:
# alternative to tf.newaxis, expand on the final axis if axis is -1
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[15],
        [ 5]],

       [[ 9],
        [21]]])>

In [16]:
# alternative to tf.newaxis, 0 is the front of the tensor
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[15,  5],
        [ 9, 21]]])>

In [17]:
# alternative to tf.newaxis, 1 is in the middle in this demo
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[15,  5]],

       [[ 9, 21]]])>

### Manipulating tensors (tensor operations)
**Basic operations**
`+`, `-`, `*`

In [18]:
#  You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10 # adds 10 to everything in the tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [19]:
# original tensor is unchanged
# if we want to add 10 we must overwrite the original tensor like a += 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [20]:
# multiply tensor by 10
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [21]:
# subtract 10 from each element in the tensor
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [22]:
# We can use the tensorflow built-in function too, this will run on the GPU
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [23]:
# the original tensor is unchanged still, make sure we overwrite it when we need to
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

### Matrix Multiplication
In machine learning, matrix multiplication is one of the most common tensor operations

There are 2 main rules for our tensors that are required for them to be multiplied together.
1. The inner dimensions must match
2. the resulting matrix has the shape of the inner dimensions

if the inner dimensions don't match we can utilize matrix transposition to re shape our matrix so that the dimensions match for matrix multiplication

In [24]:
# matrix multiplication

tf.linalg.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [25]:
# Matrix Multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [26]:
# tensor a example
tensor_a = tf.constant([
    [1,2,5],
    [7,2,1],
    [3,3,3]
])

# tensor b example
tensor_b = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

# tensor c example
tensor_c = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])


# matrix multiply tensor a and b
tensor_a @ tensor_b
#tf.linalg.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

## Example of mismatched dimensions
Utilizing Transpose to maintain data order

In [27]:
# tensor b example
tensor_d = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

# tensor c example
tensor_e = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

# we must transpose one of these tensors so that the inner dimensions are the same
print(tensor_d)
tensor_d = tf.transpose(tensor_d)
print(tensor_d)
tf.linalg.matmul(tensor_d, tensor_e)

tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 46,  65],
       [ 65, 138]])>

## Different way to reshape dimensions of a matrix 
Though will reorder/shuffle the elements differently to fit the shape

In [28]:


# tensor b example
tensor_f = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

# tensor c example
tensor_g = tf.constant([
    [3, 5],
    [6, 7],
    [1, 8]
])

print(tensor_f)
tensor_f = tf.reshape(tensor_f, shape=(2,3))
print(tensor_f)
tf.linalg.matmul(tensor_f, tensor_g)

tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 45,  98],
       [ 35, 106]])>

**The dot product**
Matrix multiplication is also referred to as the dot product.
You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [29]:
x = tf.constant([
    [1,2],
    [3,4],
    [5, 6]
])

y = tf.constant([
    [7,8],
    [9,10],
    [11, 12]
])

x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [30]:
# Perform the dot product on X and Y (requires X or Y to be tranposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [31]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [32]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(x, tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [35]:
# find the variance of our tensor
tf.math.reduce_variance(x)

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'